yaml:
  esonero:
    - detrazione: 0.07
      soglia: 1923
    - detrazione: 0.06
      soglia: 2692
  tassazione_irpef:
    anno_riferimento: 2026
    scaglioni:
      - nome: "PrimaFascia"
        low: 0
        high: 28000
        rate: 0.23
      - nome: "SecondaFascia"
        low: 28001
        high: 50000
        rate: 0.33
      - nome: "TerzaFascia"
        low: 50001
        high: 0  # 'null' indica che non c'è un limite superiore (oltre i 50k)
        rate: 0.43
  detrazioni:
    - low: 0
      high: 15000
      base: 1955
    - low: 15000
      high: 28000
      base: 1910
      increment: 1190
      increment_op: "sum"
    - low: 28000
      high: 50000
      base: 1910
      increment: 1
      increment_op: "multiply"
    - base: 65
      low: 25000
      high: 35000
      increment_op: "sum"
  cuneo_fiscale:
    - low: 0
      high: 8500
      rate: 0.071
    - low: 8500
      high: 15000
      rate: 0.053
    - low: 15000
      high: 20000
      rate: 0.048
    - low: 20000
      high: 32000
      flat_benefit: 1000
    - low: 32000
      high: 40000
      flat_benefit: 1000
      reduction_rate: 0.125
  contributi_dipendente:
    aliquota_base: 0.0919
    aliquota_solidarieta: 0.1019
    soglia_solidarieta: 56000